before_script:
  - cd terraform
  - mkdir creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json

stages:
  - terraform

terraform:
  tags:
    - docker
  stage: terraform
  script:
    - ./terraform init
    - ./terraform apply