before_script:
  - cd terraform
  - mkdir creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json

stages:
  - terraform

terraform:
  tags:
    - docker
  stage: terraform
  services: 
      - docker:dind
  image: docker
  script:
    - bash ./terraform init
    - bash  ./terraform apply