before_script:
  - mkdir terraform/creds
  - echo $SERVICEACCOUNT | base64 -d > terraform/creds/serviceaccount.json
  - echo $SSH_KEY_PUB | base64 -d > terraform/creds/id_rsa.pub
  - echo $SSH_KEY | base64 -d > terraform/creds/id_rsa
  - echo $VAULT_PASS | base64 -d > ansible/vault_pass

stages:
  - run

run:
  tags:
    - docker
  stage: run
  services: 
      - docker:dind
  image: docker
  script:
    - ./run.sh