before_script:
  - cd terraform
  - mkdir creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  - echo $SSH_KEY_PUB | base64 -d > ./creds/id_rsa.pub
  - echo $SSH_KEY | base64 -d > ./creds/id_rsa

stages:
  - terraform

terraform:
  tags:
    - docker
  stage: terraform
  services: 
      - docker:dind
  image: docker
  script:
    - ./terraform init
    - ./terraform apply -auto-approve