
- name: copy blue index.html
  copy:
    src: "{{ blue_index }}"
    dest: "{{ blue_dir }}/index.html"

- name: run blue docker container
  docker_compose:
    project_name: "blue"
    definition:
      version: "3"
      services:
        blue:
          image: "{{ blue_image }}"
          volumes:
          - "{{ blue_dir }}:{{ blue_dir }}"
          deploy:
            replicas: "{{ blue_replicas }}"
          ports: "{{ blue_ports }}"
        prometheus:
          image: "{{ blue_prometheus_image }}"
          ports: "{{ blue_prometheus_ports }}"
          command:
          - --config.file={{ blue_prometheus_config }}
          volumes:
          - "{{ blue_prometheus_config_dir }}:{{ blue_prometheus_config_dir }}:ro"
          depends_on:
          - blue

- name: copy prometheus config template
  template:
    src: "prometheus.yml"
    dest: "{{ blue_prometheus_config }}"

          

